/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6595. Copyright MediaTek Inc. (C) 2013.
 * Mon Jan  9 03:28:22 2017
 * Do Not Modify the File.
 */

#define GPIO_DVDD_BPI     GPIO_VIO18
#define GPIO_DVDD_EXMD     GPIO_VIO18


