/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6595. Copyright MediaTek Inc. (C) 2013.
 * Mon Jan  9 03:28:22 2017
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_TEMPERATURE_CHANNEL     0


#endif //_CUST_AUXADC_TOOL_H


